
##
## Export all variables to sub-invocation
##
export

bootstrap:
	$(REBAR) -v create \
			template_dir=$(DEPS_DIR)/node_package/priv/templates \
			template_vars=$(BASE_DIR)/pkg.vars.config template=osx
	make -f Makefile
